# Generated by Django 4.0.4 on 2022-06-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='the first name of the professor', max_length=50)),
                ('lastname', models.CharField(help_text='the last name of the professor', max_length=50)),
                ('module', models.CharField(help_text='the module he teaches', max_length=30)),
            ],
        ),
    ]
