# Generated by Django 4.0.4 on 2022-06-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='model1',
            name='module',
        ),
        migrations.AddField(
            model_name='model1',
            name='email',
            field=models.EmailField(help_text='the prof mail', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='model1',
            name='firstname',
            field=models.CharField(help_text='the first name of the professor', max_length=30),
        ),
        migrations.AlterField(
            model_name='model1',
            name='lastname',
            field=models.CharField(help_text='the last name of the professor', max_length=30),
        ),
    ]
