# Generated by Django 4.0.4 on 2022-06-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_model2_remove_model1_module_model1_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='promo',
            field=models.CharField(help_text='promo', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='model2',
            name='specialty',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='model2',
            name='module',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
